import type { ImageAsset, Sourced } from "./types";

export type TileTint = "blue" | "yellow" | "green" | "pink" | "purple" | "neutral";

export interface InventoryTile extends Sourced {
  id: string;
  eyebrow: string;
  index: string;
  title: string;
  body: string | null;
  image: ImageAsset | null;
  tint: TileTint;
  area: { col: string; row: string };
  fit: "contain-bottom" | "cover" | "cover-scrim";
  layout: "text-top" | "image-top" | "image-left" | "text-left" | "overlay";
  overlay?: boolean;
}

export const inventoryTiles: InventoryTile[] = [
  {
    id: "german-hangars",
    eyebrow: "Infrastructure",
    index: "01",
    title: "German Hangars",
    body: "Clear-span aluminium hangars imported for large-format deployment. Column-free interiors carry staging, seating and services without breaking a sightline.",
    image: {
      src: "/media/projects/2x/eima-agrimach-2024.webp",
      width: 1600,
      height: 900,
      alt: "German Hangars",
      clearance: "representative",
    },
    tint: "blue",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "scaffolding",
    eyebrow: "Scaffolding",
    index: "02",
    title: "Ring Lock Scaffolding",
    body: "Large Event Portable Stage and Concert Stage featuring a heavy-duty ringlock structure for safe, stable, and professional event setups.",
    image: {
      src: "/media/inventory-lighting.25f99edf.webp",
      width: 1600,
      height: 900,
      alt: "Ring Lock Scaffolding",
      clearance: "representative",
    },
    tint: "yellow",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "wooden-platforms",
    eyebrow: "Ground Works",
    index: "03",
    title: "Wooden Platforms",
    body: "Levelled wooden platforms and decking over a scaffold sub-frame, carpeted to finish. Ten lakh square feet in stock, laid across ground that is rarely flat.",
    image: {
      src: "/media/projects/2x/kanha-shanti-vanam-tent-city.webp",
      width: 1600,
      height: 900,
      alt: "Wooden Platforms",
      clearance: "representative",
    },
    tint: "yellow",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "octonorm-stalls",
    eyebrow: "Fabrication",
    index: "04",
    title: "Octonorm Stalls",
    body: "Rapid-deployment exhibition stalls engineered from premium German Octonorm profiles, offering clean lines and seamless branding integration.",
    image: {
      src: "/media/projects/2x/abs-education-fair.webp",
      width: 1600,
      height: 900,
      alt: "Octonorm Stalls",
      clearance: "representative",
    },
    tint: "green",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "maxima-stalls",
    eyebrow: "Fabrication",
    index: "05",
    title: "Maxima Stalls",
    body: "Heavy-duty Maxima profile systems for custom, large-format exhibition pavilions. Supports double-height structures and extensive overhead branding.",
    image: {
      src: "/media/projects/2x/collegedunia-education-fair.webp",
      width: 1600,
      height: 900,
      alt: "Maxima Stalls",
      clearance: "representative",
    },
    tint: "green",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "staging-dais",
    eyebrow: "Audience",
    index: "06",
    title: "Staging & Dais",
    body: "Heavy-duty modular staging systems engineered for high load capacities, accommodating everything from cultural performances to heavy equipment displays.",
    image: {
      src: "/media/projects/2x/isgcon-2023.webp",
      width: 1600,
      height: 900,
      alt: "Staging & Dais",
      clearance: "representative",
    },
    tint: "purple",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "seating-solutions",
    eyebrow: "Audience",
    index: "07",
    title: "Seating Solutions",
    body: "Audience seating, barricading and crowd routing for gatherings from a few hundred to several thousand, set out to the sightlines the stage needs.",
    image: {
      src: "/media/projects/2x/fc-expo-2024.webp",
      width: 1600,
      height: 900,
      alt: "Seating Solutions",
      clearance: "representative",
    },
    tint: "purple",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "climate-control",
    eyebrow: "Climate",
    index: "08",
    title: "Climate Control",
    body: "Industrial-grade HVAC units and spot cooling systems to maintain comfortable temperatures in temporary structures, even during peak summer.",
    image: {
      src: "/media/projects/2x/vaidic-dharma-navaratri.webp",
      width: 1600,
      height: 900,
      alt: "Climate Control",
      clearance: "representative",
    },
    tint: "blue",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "crowd-barricades",
    eyebrow: "Safety",
    index: "09",
    title: "Crowd Barricades",
    body: "Heavy-gauge interlocking galvanized steel barricades designed to establish secure perimeters, sterile VIP corridors, and high-density crowd distribution lanes.",
    image: {
      src: "/media/projects/2x/la-renon-company-event.webp",
      width: 1600,
      height: 900,
      alt: "Crowd Barricades",
      clearance: "representative",
    },
    tint: "neutral",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "lighting-av",
    eyebrow: "Lighting",
    index: "10",
    title: "Lighting & AV",
    body: "Truss, rigging, stage lighting, line-array sound and LED fascia, specified and operated by our own technicians.",
    image: {
      src: "/media/inventory/lighting_av.jpg",
      width: 1600,
      height: 900,
      alt: "Lighting & AV",
      clearance: "representative",
    },
    tint: "neutral",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "generators-power",
    eyebrow: "Power",
    index: "11",
    title: "Generators & Power",
    body: "Industrial-grade acoustic diesel generators delivering uncompromised, redundant power for massive temporary setups.",
    image: {
      src: "/media/projects/2x/hampi-utsav-2024.webp",
      width: 1600,
      height: 900,
      alt: "Generators & Power",
      clearance: "representative",
    },
    tint: "yellow",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "logistics-transport",
    eyebrow: "Logistics",
    index: "12",
    title: "Logistics & Transport",
    body: "Raja Enterprises operates our own fleet of multi-axle goods carriers, specialized transport trucks, and mobile cranes.",
    image: {
      src: "/media/projects/2x/krishi-mela-2024-25.webp",
      width: 1600,
      height: 900,
      alt: "Logistics & Transport",
      clearance: "representative",
    },
    tint: "green",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
  {
    id: "catering",
    eyebrow: "Hospitality",
    index: "13",
    title: "Catering Services",
    body: "Complete food and beverage infrastructure, from hygienic prep kitchens to elegant buffet setups serving thousands of guests seamlessly.",
    image: {
      src: "/media/projects/2x/pourakarmika-samavesha.webp",
      width: 1600,
      height: 900,
      alt: "Catering Services",
      clearance: "representative",
    },
    tint: "pink",
    area: { col: "1 / 2", row: "1 / 2" },
    fit: "cover",
    layout: "image-top",
    status: "approved",
  },
];

export const inventoryIntro = {
  eyebrow: ["What", "we deploy"] as const,
  statement: [
    { text: "Owned inventory. " },
    { text: "In-house", accent: true },
    { text: " crew. One contract." },
  ],
  cta: { label: "View full inventory", href: "/inventory" as string | null },
};

export const inventoryPhotoSources = [
  { slug: "inventory-german-hanger", source: "pexels", id: "36839425", url: "https://www.pexels.com/photo/36839425/" },
  { slug: "inventory-wooden-floor", source: "pexels", id: "16820353", url: "https://www.pexels.com/photo/16820353/" },
  { slug: "inventory-octonorm-stalls", source: "pexels", id: "35138560", url: "https://www.pexels.com/photo/35138560/" },
  { slug: "inventory-lighting", source: "pexels", id: "12787862", url: "https://www.pexels.com/photo/12787862/" },
  { slug: "inventory-stage", source: "pexels", id: "16859956", url: "https://www.pexels.com/photo/16859956/" },
  { slug: "inventory-catering", source: "pexels", id: "29086309", url: "https://www.pexels.com/photo/29086309/" },
] as const;
